### PR TITLE
chore: added types for lookup function

### PR DESCRIPTION
**Pull request by ZayneLiu**
- added JS type defs
- added TS types

### CODE REVIEW

**Comment by ZayneLiu** [comment]
@sapics Hi there, I've added types for the lookup function, whenever you are free, could you take a look and let me know if anything doesn't look right?

Also, it's probably worth converting to source files to TS instead, given you could still write JS in `.ts` files, but then I'm not familiar with how you've set up everything, so let me know what you think about this.

**Comment by sapics** [comment]
Thanks @ZayneLiu for great work!

> Also, it's probably worth converting to source files to TS instead, given you could still write JS in .ts files,
> and we can type it in the source file directly, but then I'm not familiar with how you've set up everything, so let me know what you think about this.

Sorry, I have few experiences to use ESM and I have never used typescript, thus, I have few experiences to recent js language.
There is no problem with creating it in `.ts`, as there are some requests to write it in typescript.

The only thing I am concerned about is the performance loss due to the overhead created when compiling from typescript to js.
Can we assume that they are almost the same with respect to performance?

**Comment by ZayneLiu** [comment]
@sapics 
Thanks for getting back to me, and accepting the PR.

> The only thing I am concerned about is the performance loss due to the overhead created when compiling from typescript to js. Can we assume that they are almost the same with respect to performance?

There shouldn't be any loss in performance, the runtime will still be js, compilation happens at build time which should not affect the shipped package, unless I'm wrong on that.

That being said, we can always give it a try and benchmark the two.



I use typescript on a daily basis, but I'm new to packaging, so if you could let me know 
- What's needed in terms of publishing the package?
- Is there any script I can use to check/test if the setup would work in a typical usecase (`npm i`)?
- Anything else you are concerned about / want addressed?

I could probably try and set it up.

**Comment by sapics** [comment]
I looked at some blogs (written in japanese ;)) to create a package from typescript.
My impression was that the typescript was compiled to produce the similar final product as the current one.
I would like to know if there is any missing content or inconvenience in the current output itself.

**Comment by ZayneLiu** [comment]
For the most part, it's to do with typing the whole thing, as js itself provides little/none static type checking, which makes typing the output of a `.js` function challenging.

We would need to go through each point when an object is updated, and derive the final type for it. And a little bit of guesswork, as for the most part js objects are of type `any`.

Problem occurs if/when we change the API, the type definitions would then be out-of-date, and we'd have no warning.


What Typescript can do for us in this case are,
- Stability, most types are known statically. And we'd get warnings if anything is out-of-place.
- Better/Up-to-date types. Since the types are native ts, they should never be out-of-sync.

Working with ts sometimes can be painful, but with restrictions comes predictability.

**Comment by sapics** [comment]
Thanks for description about typescript!
I understand that users need ts for stability.

**Pull request merged**
